# serial number of the sensors can be read from the terminal once the EM tracker is initialized
sensor_config:
  - sensor:
      name: probe_1
      serial_number: 39B33002       # CSTAR probe - yellow cable
      srom_filename: None
      load_srom: false
      tran_filename: None
      load_tran: false              # if false, identity tranformation is used

  - sensor:
      name: probe_2
      serial_number: 39B33003       # SPL probe - black cable
      srom_filename: None
      load_srom: false
      tran_filename: None
      load_tran: false              # if false, identity tranformation is useds

  - sensor:
      name: probe_3
      serial_number: 3E331C04       # CSTAR small probe - black body
      srom_filename: None
      load_srom: false
      tran_filename: None
      load_tran: false              # if false, identity tranformation is useds

  - sensor: ## ICEBot tip sensor ##
      name: tool
      serial_number: 3E803401       
      srom_filename: None
      load_srom: false
      tran_filename: ICEBot_bend_tip_610029.csv
      load_tran: true

  - sensor: ## ICEBot support refrence ##
      name: base
      serial_number: 3DDD6805         
      srom_filename: None
      load_srom: false
      tran_filename: ICEBot_ref_610029.csv
      load_tran: true

  # - sensor: ## CSTARBot tip sensor ##
  #     name: tool  
  #     serial_number: 39B33001
  #     srom_filename: None
  #     load_srom: false
  #     tran_filename: CSTARBot_bend_tip_610029.csv
  #     load_tran: true

  # - sensor:  ## CSTAR catheter support refrence ##
  #     name: base
  #     serial_number: 35A23801      
  #     srom_filename: None
  #     load_srom: false
  #     tran_filename: CSTARBot_ref_8700468.csv
  #     load_tran: true

  # - sensor: ## Abdominal phantom refrence ##
  #   name: reference
  #   serial_number: 37911000       
  #   srom_filename: 
  #   load_srom: false
  #   tran_filename: 
  #   load_tran: false

  # - sensor: ## Handheld CTR body reference ##
  #     name: reference
  #     serial_number: 3B2A8800       
  #     srom_filename: 
  #     load_srom: false
  #     tran_filename: 
  #     load_tran: false

